# services.yaml

parameters:

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # App\Service\ExchangeRateService will automatically get the HttpClientInterface injected by Symfony
    App\Service\ExchangeRateService:
        arguments:
            $httpClient: '@http_client'

    # App\Service\CommissionCalculator: Automatically get dependencies injected
    App\Service\CommissionCalculator:
        arguments:
            $exchangeRateService: '@App\Service\ExchangeRateService'
            $commissionRulesService: '@App\Service\CommissionRulesService'

    # CommissionRulesService
    App\Service\CommissionRulesService: ~

    # If you have a custom command, register it
    App\Command\CalculateCommissionCommand:
        arguments:
            $calculator: '@App\Service\CommissionCalculator'
        tags:
            - { name: 'console.command' }

    # HttpClient service is automatically provided by Symfony. No need to define it here.
